version: 1.0.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: F5CTc3/bSmMHKRW3d4pOSQu5roNE4RNb4wspqcdWDt8nCd3x2hR7nDAYEywofdn+
notifications:
- provider: Slack
  auth_token:
    secure: Ec+xQWO7tydVydZglSYdntEN5vhti5g5fUmXE+lIYT+CusdHW9QNi3QcJzJU7p76F8O3jb5x+2gFWvuNZLOWkg==
  channel: '#builds'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true